# Generated by Django 4.2 on 2023-04-22 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users_event", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Participants",
            new_name="Participant",
        ),
        migrations.RenameModel(
            old_name="Ratings",
            new_name="Rating",
        ),
        migrations.RemoveField(
            model_name="event",
            name="rating",
        ),
        migrations.AddField(
            model_name="event",
            name="rating_event",
            field=models.ManyToManyField(
                related_name="rating_event",
                through="users_event.Rating",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
