# Generated by Django 4.2 on 2023-04-23 16:27

from django.db import migrations, models
import users_event.models


class Migration(migrations.Migration):
    dependencies = [
        ("users_event", "0002_rename_participants_participant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="photo",
            field=models.ImageField(
                upload_to=users_event.models.get_note_image_path,
                verbose_name="Картинка",
            ),
        ),
    ]
