# Generated by Django 4.2 on 2023-04-23 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_event", "0003_alter_event_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="is_organizer",
            new_name="organizer",
        ),
    ]
