# Generated by Django 4.2 on 2023-04-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_event", "0004_rename_is_organizer_event_organizer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="is_passed",
            field=models.BooleanField(default=False),
        ),
    ]
