# Generated by Django 4.2 on 2023-05-04 18:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users_event", "0005_alter_event_is_passed"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("title", "user")},
        ),
    ]
