# Generated by Django 4.2 on 2023-04-11 19:31

import authorisation_token.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authorisation_token", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", authorisation_token.models.UserManager()),
            ],
        ),
    ]
