version: '3'
services:
  app:
    image: eventloop:latest
    ports:
      - "8000:8000"
    build:
      dockerfile: backend/deploy/app/Dockerfile
      context: ..
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
    volumes:
      - media:/app/media/
  postgres:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "eventloop"
      POSTGRES_USER: "eventloop"
      POSTGRES_PASSWORD: "Amir2003"
    volumes:
      - "db:/var/lib/postgresql/data"
  redis:
    image: redis:7-alpine
    ports:
      - "6377:6379"
volumes:
  db:
  redis:
  media: