version: '3'
services:
  app:
    image: eventloop:latest
    ports:
      - "8000:8000"
    build:
      dockerfile: deploy/app/back/Dockerfile
      context: ..
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      REDIS_WEBSOCKET_HOST: redis_web_sockets
      REDIS_WEBSOCKET_PORT: "6379"
    volumes:
      - media:/app/backend/media/
  frontend:
    image: eventloop_front:latest
    build:
      context: ..
      dockerfile: deploy/app/front/Dockerfile
    ports:
      - "8080:80"
  postgres:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "eventloop"
      POSTGRES_USER: "eventloop"
      POSTGRES_PASSWORD: "Amir2003"
    volumes:
      - "db:/var/lib/postgresql/data"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  redis_web_sockets:
    image: redis:7-alpine
    ports:
      - "6378:6379"
  celery:
    build:
      dockerfile: deploy/app/back/Dockerfile
      context: ..
    depends_on:
      - app
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
    command: [ "celery", "-A", "eventloop", "worker", "-l", "info" ]
  celery_beat:
    build:
      dockerfile: deploy/app/back/Dockerfile
      context: ..
    depends_on:
      - app
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
    command: [ "celery", "-A", "eventloop", "beat", "-l", "info" ]
volumes:
  db:
  redis:
  media:
  static: